# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "To create development certificate and provisioning profile"
  lane :get_dev_certs do
    cert(
          development: true
      )
    sigh(
          development: true
      )
  end

  desc "To export app to AppStoreConnect"
  lane :export_app do
    gym(
      workspace: "Mailmo.xcworkspace",
      scheme: "Mailmo",
      clean: true,
      export_xcargs: "-allowProvisioningUpdates",
      output_name: "Mailmo.ipa"
    )
  end

  desc "To send app to AppStoreConnect"
  lane :upload_app do
    deliver(
      ipa: "Mailmo.ipa",
      skip_screenshots: true,
      skip_metadata: true,
      skip_app_version_update: true,
      force: true
    )
  end

  desc "Releases app to the AppStore"
  lane :release_app do
    export_app
    upload_app
  end

end
